# Spiderbot: Web Validation Robot
# Copyright (C) 2015  Julio Martínez Martínez-Checa

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Contact: julioxus@gmail.com

# University of Granada, hereby disclaims all copyright
# interest in the program `Spiderbot' written 
# by Julio Martínez Martínez-Checa.

# signature of Julio Martínez Martínez-Checa, 23 June 2015
# Julio Martínez Martínez-Checa, Student at the University of Granada.

application: spiderbot-ugr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: server.application


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: lxml
  version: latest
